// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYme9h1WUf5V52YJxJdjh_mNNzoZN73C0',
    appId: '1:678415324438:web:450e4ee34b5f24dd91ac37',
    messagingSenderId: '678415324438',
    projectId: 'chat-app-822e1',
    authDomain: 'chat-app-822e1.firebaseapp.com',
    storageBucket: 'chat-app-822e1.appspot.com',
    measurementId: 'G-7YHNG7KQ7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG8WuG5b-MO9tmTyyi08B8MH_xshrPUyI',
    appId: '1:678415324438:android:f39379fe5f3dbf2291ac37',
    messagingSenderId: '678415324438',
    projectId: 'chat-app-822e1',
    storageBucket: 'chat-app-822e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhARb8AI2ImR0oX4FgMqq44b01lVpiqQA',
    appId: '1:678415324438:ios:cd82e0a70c2b7dc291ac37',
    messagingSenderId: '678415324438',
    projectId: 'chat-app-822e1',
    storageBucket: 'chat-app-822e1.appspot.com',
    iosBundleId: 'com.example.genie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhARb8AI2ImR0oX4FgMqq44b01lVpiqQA',
    appId: '1:678415324438:ios:076e24e6d9a97dfe91ac37',
    messagingSenderId: '678415324438',
    projectId: 'chat-app-822e1',
    storageBucket: 'chat-app-822e1.appspot.com',
    iosBundleId: 'com.example.genie.RunnerTests',
  );
}
